/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.login;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author XYZ
 */
public class GoRide extends javax.swing.JFrame {

    /**
     * Creates new form GoRide
     */
    Date date = new Date();
    int Biaya=5000;
    SimpleDateFormat formater1 = new SimpleDateFormat("dd-MM-yyyy HH:mm");
    String datenow = formater1.format(date);
    String voucher = "ovomdn";
    public GoRide(String name) {
        initComponents();
        jLabel_uname.setText(name);
        jLabel_date.setText(datenow);
        LoginForm lf = new LoginForm();
        this.setLocationRelativeTo(null);
        System.out.println(getClass());
        
        //jTextField_Biaya.setText(String.valueOf(Biaya));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Biaya = new javax.swing.JTextField();
        jLabel_uname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField_Voucher = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton_voucher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_date.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("GO-RIDE");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Lokasi", "Medan Timur", "Medan Barat", "Medan Selatan", "Medan Tengah" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Lokasi :");

        jLabel3.setText("Tujuan :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tujuan", "Medan Timur", "Medan Barat", "Medan Selatan", "Medan Tengah" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Biaya :");

        jLabel_uname.setText("Uname");

        jLabel5.setText("Nama :");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("PESAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Voucher :");

        jButton_voucher.setText("Gunakan");
        jButton_voucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voucherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_date)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_uname)
                            .addComponent(jTextField_Voucher)
                            .addComponent(jTextField_Biaya))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_voucher)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_uname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Voucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton_voucher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String uname = jLabel_uname.getText();
        String lokasi = String.valueOf(jComboBox1.getSelectedItem());
        String tujuan = String.valueOf(jComboBox2.getSelectedItem());
        String voucher = jTextField_Voucher.getText();
        int biaya = Integer.valueOf(jTextField_Biaya.getText());
        java.util.Date date=new java.util.Date();
        java.sql.Date sqlDate=new java.sql.Date(date.getTime());
        java.sql.Timestamp sqlTime=new java.sql.Timestamp(date.getTime());
        
        PreparedStatement ps;
        ResultSet rs;
        String query = "INSERT INTO `goride_table`( `uname`,`tanggal`,`jam`,`lokasi`, `tujuan`, `voucher`, `biaya`) VALUES (?,?,?,?,?,?,?)";
        
        try {
            ps = My_CNX.getConnection().prepareStatement(query);
            ps.setString(1, uname);
            ps.setDate(2, sqlDate);
            ps.setTimestamp(3, sqlTime);
            ps.setString(4, lokasi);
            ps.setString(5, tujuan);
            ps.setString(6, voucher);
            ps.setInt(7, biaya);
            if(ps.executeUpdate() != 0){
                JOptionPane.showMessageDialog(null, "Pesanan Sukses");
            }else{
                JOptionPane.showMessageDialog(null, "Error: Sistem Sibuk");
            }
        } catch (HeadlessException | SQLException ex) {
            Logger.getLogger(RegisForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_voucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voucherActionPerformed
        String getvoucher = jTextField_Voucher.getText();
        if(voucher.equals(getvoucher)){
            JOptionPane.showMessageDialog(null, "voucher sukses");
            Biaya=Integer.valueOf(jTextField_Biaya.getText());
            Biaya-=(Biaya*0.25);
            jTextField_Biaya.setText(String.valueOf(Biaya));
        }
        else{
            JOptionPane.showMessageDialog(null, "Voucher salah");
        }
    }//GEN-LAST:event_jButton_voucherActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if(jComboBox1.getSelectedItem()=="Medan Timur" && jComboBox2.getSelectedItem()=="Medan Barat" ||
            jComboBox1.getSelectedItem()=="Medan Barat" && jComboBox2.getSelectedItem()=="Medan Timur")
        Biaya = 5000;
        else if(jComboBox1.getSelectedItem()=="Medan Timur" && jComboBox2.getSelectedItem()=="Medan Tengah" ||
            jComboBox1.getSelectedItem()=="Medan Tengah" && jComboBox2.getSelectedItem()=="Medan Timur")
        Biaya = 10000;
        else if(jComboBox1.getSelectedItem()=="Medan Timur" && jComboBox2.getSelectedItem()=="Medan Selatan" ||
            jComboBox1.getSelectedItem()=="Medan Selatan" && jComboBox2.getSelectedItem()=="Medan Timur")
        Biaya = 15000;
        else if(jComboBox1.getSelectedItem()=="Medan Barat" && jComboBox2.getSelectedItem()=="Medan Selatan" ||
            jComboBox1.getSelectedItem()=="Medan Selatan" && jComboBox2.getSelectedItem()=="Medan Barat")
        Biaya = 20000;
        else if (jComboBox1.getSelectedItem()=="Medan Barat" && jComboBox2.getSelectedItem()=="Medan Tengah" ||
            jComboBox1.getSelectedItem()=="Medan Tengah" && jComboBox2.getSelectedItem()=="Medan Barat")
        Biaya = 25000;
        else
        Biaya = 30000;
        jTextField_Biaya.setText(String.valueOf(Biaya));
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox1.removeItem("Pilih Lokasi");
        if(jComboBox1.getSelectedItem()=="Medan Timur")
        {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Medan Barat");
            jComboBox2.addItem("Medan Tengah");
            jComboBox2.addItem("Medan Selatan");
        }
        else if(jComboBox1.getSelectedItem()=="Medan Barat")
        {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Medan Timur");
            jComboBox2.addItem("Medan Tengah");
            jComboBox2.addItem("Medan Selatan");
        }

        else if(jComboBox1.getSelectedItem()=="Medan Selatan")
        {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Medan Timur");
            jComboBox2.addItem("Medan Barat");
            jComboBox2.addItem("Medan Tengah");
        }
        else
        {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Medan Timur");
            jComboBox2.addItem("Medan Barat");
            jComboBox2.addItem("Medan Selatan");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoRide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GoRide("abc").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_voucher;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_date;
    private javax.swing.JLabel jLabel_uname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_Biaya;
    private javax.swing.JTextField jTextField_Voucher;
    // End of variables declaration//GEN-END:variables
}
